module(
    name = "stm32_bazel_development",
    version = "1.0",
)

bazel_dep(name = "rules_cc", version = "0.0.17")
bazel_dep(name = "rules_shell", version = "0.3.0")
bazel_dep(name = "toolchains_arm_gnu", version = "1.0.0")

arm_toolchain = use_extension("@toolchains_arm_gnu//:extensions.bzl", "arm_toolchain")

# This tells the extension to fetch the arm-none-eabi-gcc toolchain
arm_toolchain.arm_none_eabi() 

# Import the generated repository into your module's scope
use_repo(arm_toolchain, "arm_none_eabi")

# Register the toolchain so Bazel can use it for cross-compilation
register_toolchains("@arm_none_eabi//toolchain:all")