# This file defines the ST HAL driver library.
package(default_visibility = ["//:__subpackages__"])

# Define the C/C++ library target for the HAL
cc_library(
    name = "hal_drivers",
    
    # Add all the .c source files used by the HAL
    srcs = glob([
        "../../Drivers/STM32G4xx_HAL_Driver/Src/*.c",
    ]),
    
    # Add all the .h header files.
    hdrs = glob([
        "../../Core/Inc/*.h",
        "../../Drivers/STM32G4xx_HAL_Driver/Inc/*.h",
        "../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy/*.h",
        "../../Drivers/CMSIS/Device/ST/STM32G4xx/Include/*.h",
        "../../Drivers/CMSIS/Include/*.h",
    ]),
    
    # Tell Bazel what to add to the include path for anyone who depends on this.
    includes = [
        "../../Core/Inc",
        "../../Drivers/STM32G4xx_HAL_Driver/Inc",
        "../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy",
        "../../Drivers/CMSIS/Device/ST/STM32G4xx/Include",
        "../../Drivers/CMSIS/Include",
    ],
    
    # Add the compiler flags and defines needed to compile this library.
    copts = [
        "-DSTM32G441xx",
        "-DUSE_HAL_DRIVER",
        "-mcpu=cortex-m4",
        "-mthumb",
        "-mfloat-abi=hard",
        "-mfpu=fpv4-sp-d16",
    ],
)